jobs:
  include:
    - stage: tests
      language: node_js
      node_js:
        - "7"
      install:
        - npm install
      before_script: cp src/config.js.EXAMPLE src/config.js
      script: npm run test

    - stage: deploy
      if: branch = master AND type != pull_request
      language: node_js
      node_js:
        - "7"
      install:
        - npm install
      before_script: cp src/config.js.EXAMPLE src/config.js
      script: npm run prod

      deploy:
        provider: pages
        skip-cleanup: true
        github-token: $GITHUB_TOKEN
        keep-history: true
        local-dir: public
    - stage: release
      if: branch = master AND type != pull_request
      language: node_js
      node_js: node
      script:
        - npm install -g semantic-release
        - npm install -g @semantic-release/changelog
        - npm install -g @semantic-release/git
      deploy:
        provider: script
        skip-cleanup: true
        script: semantic-release

