language: node_js
node_js:
  - "iojs"
  - "7"

jobs:
  include:
    - stage: tests
      language: node_js
      node_js:
        - "iojs"
        - "7"
      install:
        - npm install
      script: npm run test

    - stage: deploy
      if: branch = master AND type != pull_request
      language: node_js
      node_js:
        - "iojs"
        - "7"
      install:
        - npm install
      script: npm run build
      deploy:
        provider: pages
        skip-cleanup: true
        github-token: $GITHUB_TOKEN
        keep-history: true
        local-dir: build