jobs:
  include:
    - stage: tests
      language: node_js
      node_js:
        - "7"
      install:
        - npm install

      before_scipt: cp config.js.EXAMPLE config.js
      script: npm run test

    - stage: deploy
      if: branch = master AND type != pull_request
      language: node_js
      node_js:
        - "7"
      install:
        - npm install
      script: npm run prod
      deploy:
        provider: pages
        skip-cleanup: true
        github-token: $GITHUB_TOKEN
        keep-history: true
        local-dir: public