//LOGIN LOGOUT
export const LOGIN = 'LOGIN';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAILURE = 'LOGIN_FAILURE';
export const LOGOUT = 'LOGOUT';
export const LOGOUT_SUCCESS = 'LOGOUT_SUCCESS';
export const LOGOUT_FAILURE = 'LOGOUT_FAILURE';
export const USER_DATA = 'USER_DATA';


//USERS
export const USER_SET_CURRENT = 'USER_SET_CURRENT';
export const USER_SET_CURRENT_FAILED = 'USER_SET_CURRENT_FAILED';

export const USER_ADD_NEW = 'USER_ADD_NEW';
export const USER_ADD_NEW_SUCCESS = 'USER_ADD_NEW_SUCCESS';
export const USER_ADD_NEW_FAILURE = 'USER_ADD_NEW_FAILURE';
export const USER_DELETE = 'USER_DELETE';
export const USER_DELETE_SUCCESS = 'USER_DELETE_SUCCESS';
export const USER_DELETE_FAILURE = 'USER_DELETE_FAILURE';
export const USER_UPDATE = 'USER_UPDATE';
export const USER_UPDATE_FAILURE = 'USER_UPDATE_FAILURE';
export const USER_UPDATE_SUCCESS = 'USER_UPDATE_SUCCESS';
export const USER_SET_ALL = 'USER_SET_ALL';
export const USER_LOADING_START = 'USER_LOADING_START';
export const USER_LOADING_SUCCESS = 'USER_LOADING_SUCCESS';
export const USER_LOADING_FAILURE = 'USER_LOADING_FAILURE';
export const USER_ERRORS = 'USER_ERRORS';
export const USER_NO_ERRORS = 'USER_NO_ERRORS';


//LOADING
export const LOADING_BEGIN = 'LOADING_BEGIN';
export const LOADING_FINISH = 'LOADING_FINISH';
export const LOADING_FAIL = 'LOADING_FAIL';
export const INIT_READY = 'INIT_READY';


//CONTAINER
export const CONTAINER_ADD_NEW = 'CONTAINER_ADD_NEW';
export const CONTAINER_ADD_NEW_SUCCESS = 'CONTAINER_ADD_NEW_SUCCESS';
export const CONTAINER_ADD_NEW_FAILURE = 'CONTAINER_ADD_NEW_FAILURE';
export const CONTAINER_DELETE = 'CONTAINER_DELETE';
export const CONTAINER_DELETE_SUCCESS = 'CONTAINER_DELETE_SUCCESS';
export const CONTAINER_DELETE_FAILURE = 'CONTAINER_DELETE_FAILURE';
export const CONTAINER_UPDATE_SUCCESS = 'CONTAINER_UPDATE_SUCCESS';
export const CONTAINER_UPDATE_FAILURE = 'CONTAINER_UPDATE_FAILURE';
export const CONTAINER_SET_ALL = 'CONTAINER_SET_ALL';
export const CONTAINER_SET_ALL_FAILURE = 'CONTAINER_SET_ALL_FAILURE';
export const CONTAINER_LOADING_START = 'CONTAINER_LOADING_START';
export const CONTAINER_LOADING_SUCCESS = 'CONTAINER_LOADING_SUCCESS';
export const CONTAINER_LOADING_FAILURE = 'CONTAINER_LOADING_FAILURE';


//HOST
export const HOST_ADD_NEW = 'HOST_ADD_NEW';
export const HOST_ADD_NEW_SUCCESS = 'HOST_ADD_NEW_SUCCESS';
export const HOST_ADD_NEW_FAILURE = 'HOST_ADD_NEW_FAILURE';
export const HOST_DELETE = 'HOST_DELETE';
export const HOST_DELETE_SUCCESS = 'HOST_DELETE_SUCCESS';
export const HOST_DELETE_FAILURE = 'HOST_DELETE_FAILURE';
export const HOST_UPDATE_SUCCESS = 'HOST_UPDATE_SUCCESS';
export const HOST_UPDATE_FAILURE = 'HOST_UPDATE_FAILURE';
export const HOST_SET_ALL = 'HOST_SET_ALL';
export const HOST_LOADING_START = 'HOST_LOADING_START';
export const HOST_LOADING_SUCCESS = 'HOST_LOADING_SUCCESS';
export const HOST_LOADING_FAILURE = 'HOST_LOADING_FAILURE';
export const HOST_AUTH_SUCCESS = 'HOST_AUTH_SUCCESS';
export const HOST_AUTH_FAILURE = 'HOST_AUTH_FAILURE';


//PROFILE
export const PROFILE_ADD_NEW = 'PROFILE_ADD_NEW';
export const PROFILE_ADD_NEW_SUCCESS = 'PROFILE_ADD_NEW_SUCCESS';
export const PROFILE_ADD_NEW_FAILURE = 'PROFILE_ADD_NEW_FAILURE';
export const PROFILE_DELETE = 'PROFILE_DELETE';
export const PROFILE_DELETE_SUCCESS = 'PROFILE_DELETE_SUCCESS';
export const PROFILE_DELETE_FAILURE = 'PROFILE_DELETE_FAILURE';
export const PROFILE_UPDATE_SUCCESS = 'PROFILE_UPDATE_SUCCESS';
export const PROFILE_UPDATE_FAILURE = 'PROFILE_UPDATE_FAILURE';
export const PROFILE_SET_ALL = 'PROFILE_SET_ALL';
export const PROFILE_SET_ALL_FAILURE = 'PROFILE_SET_ALL_FAILURE';


//IMAGE
export const IMAGE_ADD_NEW = 'IMAGE_ADD_NEW';
export const IMAGE_ADD_NEW_SUCCESS = 'IMAGE_ADD_NEW_SUCCESS';
export const IMAGE_ADD_NEW_FAILURE = 'IMAGE_ADD_NEW_FAILURE';
export const IMAGE_DELETE = 'IMAGE_DELETE';
export const IMAGE_DELETE_SUCCESS = 'IMAGE_DELETE_SUCCESS';
export const IMAGE_DELETE_FAILURE = 'IMAGE_DELETE_FAILURE';
export const IMAGE_UPDATE_SUCCESS = 'IMAGE_UPDATE_SUCCESS';
export const IMAGE_UPDATE_FAILURE = 'IMAGE_UPDATE_FAILURE';
export const IMAGE_SET_ALL = 'IMAGE_SET_ALL';
export const IMAGE_SET_ALL_FAILURE = 'IMAGE_SET_ALL_FAILURE';




/**
 * BACKUPS
 */

//BACKUP DESTINATION
export const BACKUPDEST_ADD_NEW = 'BACKUPDEST_ADD_NEW';
export const BACKUPDEST_ADD_NEW_SUCCESS = 'BACKUPDEST_ADD_NEW_SUCCESS';
export const BACKUPDEST_ADD_NEW_FAILURE = 'BACKUPDEST_ADD_NEW_FAILURE';
export const BACKUPDEST_DELETE = 'BACKUPDEST_DELETE';
export const BACKUPDEST_DELETE_SUCCESS = 'BACKUPDEST_DELETE_SUCCESS';
export const BACKUPDEST_DELETE_FAILURE = 'BACKUPDEST_DELETE_FAILURE';
export const BACKUPDEST_UPDATE_SUCCESS = 'BACKUPDEST_UPDATE_SUCCESS';
export const BACKUPDEST_UPDATE_FAILURE = 'BACKUPDEST_UPDATE_FAILURE';
export const BACKUPDEST_SET_ALL = 'BACKUPDEST_SET_ALL';
export const BACKUPDEST_ERRORS = 'BACKUPDEST_ERRORS';
export const BACKUPDEST_NO_ERRORS = 'BACKUPDEST_NO_ERRORS';



//BACKUP SCHEDULE
export const BACKUPSCHEDULE_ADD_NEW = 'BACKUPSCHEDULE_ADD_NEW';
export const BACKUPSCHEDULE_ADD_NEW_SUCCESS = 'BACKUPSCHEDULE_ADD_NEW_SUCCESS';
export const BACKUPSCHEDULE_ADD_NEW_FAILURE = 'BACKUPSCHEDULE_ADD_NEW_FAILURE';
export const BACKUPSCHEDULE_DELETE = 'BACKUPSCHEDULE_DELETE';
export const BACKUPSCHEDULE_DELETE_SUCCESS = 'BACKUPSCHEDULE_DELETE_SUCCESS';
export const BACKUPSCHEDULE_DELETE_FAILURE = 'BACKUPSCHEDULE_DELETE_FAILURE';
export const BACKUPSCHEDULE_UPDATE_SUCCESS = 'BACKUPSCHEDULE_UPDATE_SUCCESS';
export const BACKUPSCHEDULE_UPDATE_FAILURE = 'BACKUPSCHEDULE_UPDATE_FAILURE';
export const BACKUPSCHEDULE_SET_ALL = 'BACKUPSCHEDULE_SET_ALL';
export const BACKUPSCHEDULE_ERRORS = 'BACKUPSCHEDULE_ERRORS';
export const BACKUPSCHEDULE_NO_ERRORS = 'BACKUPSCHEDULE_NO_ERRORS';



//BACKUP
export const BACKUP_ADD_NEW = 'BACKUP_ADD_NEW';
export const BACKUP_ADD_NEW_SUCCESS = 'BACKUP_ADD_NEW_SUCCESS';
export const BACKUP_ADD_NEW_FAILURE = 'BACKUP_ADD_NEW_FAILURE';
export const BACKUP_DELETE = 'BACKUP_DELETE';
export const BACKUP_DELETE_SUCCESS = 'BACKUP_DELETE_SUCCESS';
export const BACKUP_DELETE_FAILURE = 'BACKUP_DELETE_FAILURE';
export const BACKUP_UPDATE_SUCCESS = 'BACKUP_UPDATE_SUCCESS';
export const BACKUP_UPDATE_FAILURE = 'BACKUP_UPDATE_FAILURE';
export const BACKUP_SET_ALL = 'BACKUP_SET_ALL';
export const BACKUP_ERRORS = 'BACKUP_ERRORS';
export const BACKUP_NO_ERRORS = 'BACKUP_NO_ERRORS';