export const WORKOUT_ADD_NEW = 'WORKOUT_ADD_NEW'
export const WORKOUT_ADD_NEW_SUCCESS = 'WORKOUT_ADD_NEW_SUCCESS'
export const WORKOUT_ADD_NEW_FAILURE = 'WORKOUT_ADD_NEW_FAILURE'
export const WORKOUT_DELETE = 'WORKOUT_DELETE'
export const WORKOUT_DELETE_SUCCESS = 'WORKOUT_DELETE_SUCCESS'
export const WORKOUT_DELETE_FAILURE = 'WORKOUT_DELETE_FAILURE'
export const WORKOUT_UPDATE_SUCCESS = 'WORKOUT_UPDATE_SUCCESS'
export const WORKOUT_SET_ALL = 'WORKOUT_SET_ALL'
export const WORKOUT_SET_META = 'WORKOUT_SET_META'
export const WORKOUT_SET_LINKS = 'WORKOUT_SET_LINKS'

export const WORKOUTPLAN_SET_CURRENT = 'WORKOUTPLAN_SET_CURRENT'

export const WORKOUTTYPE_SET_ALL = 'WORKOUTTYPE_SET_ALL'
export const HEALTHTYPE_SET_ALL = 'HEALTHTYPE_SET_ALL'
export const MENTALTYPE_SET_ALL = 'MENTALTYPE_SET_ALL'
export const PHYSICALTYPE_SET_ALL = 'PHYSICALTYPE_SET_ALL'


export const USER_SET_CURRENT = 'USER_SET_CURRENT'
export const USER_SET_ATHLETES = 'USER_SET_ATHLETES'


export const LOGIN = 'LOGIN'
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS'
export const LOGIN_FAILURE = 'LOGIN_FAILURE'
export const LOGOUT = 'LOGOUT'
export const LOGOUT_SUCCESS = 'LOGOUT_SUCCESS'
export const LOGOUT_FAILURE = 'LOGOUT_FAILURE'
export const USER_DATA = 'USER_DATA'


export const LOADING_BEGIN = 'LOADING_BEGIN'
export const LOADING_FINISH = 'LOADING_FINISH'
export const INIT_READY = 'INIT_READY'


export const CONTAINER_ADD_NEW = 'CONTAINER_ADD_NEW'
export const CONTAINER_ADD_NEW_SUCCESS = 'CONTAINER_ADD_NEW_SUCCESS'
export const CONTAINER_ADD_NEW_FAILURE = 'CONTAINER_ADD_NEW_FAILURE'
export const CONTAINER_DELETE = 'CONTAINER_DELETE'
export const CONTAINER_DELETE_SUCCESS = 'CONTAINER_DELETE_SUCCESS'
export const CONTAINER_DELETE_FAILURE = 'CONTAINER_DELETE_FAILURE'
export const CONTAINER_UPDATE_SUCCESS = 'CONTAINER_UPDATE_SUCCESS'
export const CONTAINER_SET_ALL = 'CONTAINER_SET_ALL'

export const HOST_ADD_NEW = 'HOST_ADD_NEW'
export const HOST_ADD_NEW_SUCCESS = 'HOST_ADD_NEW_SUCCESS'
export const HOST_ADD_NEW_FAILURE = 'HOST_ADD_NEW_FAILURE'
export const HOST_DELETE = 'HOST_DELETE'
export const HOST_DELETE_SUCCESS = 'HOST_DELETE_SUCCESS'
export const HOST_DELETE_FAILURE = 'HOST_DELETE_FAILURE'
export const HOST_UPDATE_SUCCESS = 'HOST_UPDATE_SUCCESS'
export const HOST_SET_ALL = 'HOST_SET_ALL'